# Generated by Django 2.1 on 2018-08-31 17:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('requestdetail', ckeditor.fields.RichTextField()),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Assigned'), (3, 'Pending'), (4, 'Closed')], default=1)),
                ('opendate', models.DateTimeField(verbose_name='date published')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Department')),
            ],
            options={
                'ordering': ['opendate'],
            },
        ),
    ]
