# Generated by Django 2.1 on 2018-08-31 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_area_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='area',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tickets.Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tickets.Item'),
            preserve_default=False,
        ),
    ]
